### ISSUE TITLE
Occasional Crash when loading world

### ISSUE THREAD

**Issue by Ritzumi** [team-abnormals/abnormals-core#66]
### Versions
Forge: 35.1.36
Abnormals_Core: 1.16.4-3.0.6
Upgrade_Aquatic: 1.16.4-3.0.0

### Description
I encountered this crash occasionally when joining a world for the first time or loading a save (I put occasional because most of the time it didn't happen). Just joining the world would make the game crash and produce crash log. However, the world isn't corrupted. I can join it again after crash and most of the times it would run normally.

### Step to reproduce
This is tricky, I am not sure what actually cause this. But, If I am correct, it is caused by thrasher via abnormal endimator?
Last time it crashed, I load my save near frozen ocean. 
I can load it normally on second attempt, also checking nearby entities and found thrasher nearby (But this time it doesn't crash) (Checked by Crash utilities).

### Attachment
Crash log: https://gist.github.com/Ritzumi/696648886feecd6399da64527a74deac
Log: https://gist.github.com/Ritzumi/2a264085dcdb60855212d9e3aa99466c

**Comment by SmellyModder** [comment]
This isn't an Abnormals Core issue. It appears to be an issue with Upgrade Aquatic or Reliquary.
Open an issue at one of those repositories.

> Last time it crashed, I load my save near frozen ocean. I can load it normally on second attempt, also checking nearby entities and found thrasher nearby (But this time it doesn't crash)

This likely isn't related, as the crash you sent should happen when a world is loaded, regardless if there are even Thrashers nearby.
My guess for the cause of the crash is that the entity's attributes aren't loaded yet when it gets them during loading the world because the Thrasher would have a max health attribute, which is what the crash seems to be reporting isn't existing.
