### ISSUE TITLE
Abnormals Core possibly breaking desert pyramid loot tables

### ISSUE THREAD

**Issue by Maltshakes** [team-abnormals/abnormals-core#68]
My desert pyramids all have empty loots chests. After installing the Blame mod and attempting once more to open a chest, it pointed me towards Abnormals Core as the cause. 

The log from Blame is in the pastebin link below. Line 1300 is what mentions Abnormals Core.

https://pastebin.com/dSEbDn09

**Comment by Maltshakes** [comment]
This also seems to affect jungle temple loot chests

**Comment by SmellyModder** [comment]
Abnormals Core is crashing, but it isn't the root of the issue. There's an error with those loot tables happening somewhere caused by another data pack. When this error occurs, it causes the loot table to be null since it couldn't be parsed, and Abnormals Core assumes that the loot table will always be nonnull, as does the forge event.
Fixing the error with the table causing it to be null will fix this crash, but I will also look into putting a null check in the event to prevent edge cases like this from happening again.
